--시퀀스를 생성할 때에는 'SEQ_'로 시작하는 것이 일반적이다.
CREATE SEQUENCE SEQ_BOARD;

--테이블 생성시 'TBL_'로 시작하거나 'T_'와 같이 시작하는 것이 일반적이다.

CREATE TABLE TBL_BOARD(
	BNO NUMBER(10),
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	WRITER VARCHAR2(100) NOT NULL,
	REGDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE,
	CONSTRAINT PK_MYBOARD PRIMARY KEY(BNO)
);

SELECT * FROM TBL_BOARD;

SELECT COUNT(*) FROM TBL_BOARD;

INSERT INTO TBL_MYBOARD (BNO, TITLE, CONTENT, WRITER)
VALUES(SEQ_MYBOARD.NEXTVAL, '테스트 제목2', '테스트 내용2', '백성민');

CREATE TABLE MYFILES(
	FILE_NAME VARCHAR2(100),
	BNO NUMBER(10),
	CONSTRAINT MYFILES_PK PRIMARY KEY(FILE_NAME),
	CONSTRAINT MYFILES_FK FOREIGN KEY(BNO)
	REFERENCES TBL_BOARD(BNO)
);
DROP TABLE MYFILES;
SELECT * FROM MYFILES;


SELECT * FROM MYFILES WHERE BNO = 300;
SELECT * FROM MYFILES WHERE BNO = 273;
DELETE FROM MYFILES WHERE BNO = 281;
